PARAMS = {'short_window': 35,
          'long_window': 80,
          'trade_freq': 7,
          'strike_rounding': True,
          'bid_offer_spread': 0,
          'otm_percentage': 0,
          'option_rate': 0,
          'confidence': 4,
          'base_yield': 0.055,
          'rv_start': [None, None],
          'dvol_open': [None, None],
          'sigma_open': [None, 1.1],
          'dvol_premium': [-1, 0.45],
          'is_usd': True,
          'historical_vol': True}
